### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by NaomiMariga**
This pull request explores the User interface design of the Shopping List application. Critique the user interface design in terms of looks, logic and overall feeling. 
[https://naomimariga.github.io/ShoppingList](https://naomimariga.github.io/ShoppingList/)

### CODE REVIEW

**Comment by NaomiMariga** [comment]
@grace-mugoiri Kindly review my work

**Comment by grace-mugoiri** [comment]
On first commit, I think the name "skeleton" is weird, use something like "template" .
Overall its okay.

**Comment by NaomiMariga** [comment]
@Sowayi Kindly review my work

**Comment by NaomiMariga** [comment]
@grace-mugoiri  Thank you will work on that

**Comment by puritysowayi** [comment]
The user interfaces capture all the required features. I think its been done well.

**Pull request merged**
