### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by NaomiMariga**
### What the PR does

This PR introduces the complete Shoppinglist application which allows the user to keep track of the list of items they wish to purchase as well as budget on these items. 

### Description of the Application

 The user creates an account, and upon login the user creates the a new list and adds the items of their wish in the list. The user can also edit and  delete both the list and the items. Besides, in cases of a forgotten password the user provides their registered email and a password is sent to them. This password can be change later after authentication. The data storage used is non-persistent, therefore,  it is lost once the server is restarted or the user logs out.

### Manually testing the application.

Clone the application, install the requirements ``` - pip install -r requirements.txt ``` and run the server.py file ``` python server.py ```

### CODE REVIEW

**Comment by Awinja-j** [comment]
@NaomiMariga  the .coverage and .coveragerc files still exist in this repo

**Comment by Dlelo** [comment]
Awesome application! Good Job Girl!

**Comment by ghost** [comment]
Your work is neat, code is readable, that's great. You have also integrated Travis and the pivotal tracker has been linked to your repo. Good job.

**Comment by NaomiMariga** [comment]
Thanks a lot for your inputs, I appreciate @Awinja-Andela , @Dlelo and @juhslydiah

**Pull request merged**
